@startuml
participant Front as scr
participant API as api
participant DB as db
participant Discord as dis

alt ユーザ状態が「退室」
    api->db:状態を「入室」に
    api->dis:入室通知
    api->scr:入室ログ
else ユーザ状態が「入室」&&最終更新日が現在
    api->db:状態を「退室」に
    api->dis:退室通知
    api->scr:退室ログ
else ユーザ状態が「入室」&&最終更新日が現在でない
    api->dis:入室通知
    api->scr:入室ログ
end

@enduml