@startuml
actor       Member       as men
participant Front as scr
participant API as api
participant DB as db
participant Discord as dis

men->scr:学生証スキャン
scr->api:学籍番号
api->db:ユーザid問い合わせ
db-->api:

alt User don't exist in DB
    ref over men, dis : 登録処理
else 
    ref over scr, dis : 通知処理
end
@enduml